name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and start services with Docker Compose
      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d --build

      # Run tests
      - name: Run tests for orders-service
        run: |
          docker-compose exec orders-service mvn test

      - name: Run tests for inventory-service
        run: |
          docker-compose exec inventory-service mvn test

      # Tear down services
      - name: Tear down services
        run: docker-compose down
