name: Docke CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181
        options: --health-cmd="echo ruok | nc 127.0.0.1 2181 | grep imok" --health-interval=10s --health-retries=5 --health-timeout=5s
      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        options: --health-cmd="kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list" --health-interval=10s --health-retries=5 --health-timeout=5s
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
          ALLOW_PLAINTEXT_LISTENER: "yes"
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-retries=5 --health-timeout=5s
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ordersdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker images
        run: |
          docker build -t ghcr.io/sebastianberchtold-hftm/orders-service:1.0.0 orders-service/
          docker build -t ghcr.io/sebastianberchtold-hftm/inventory-service:1.0.0 inventory-service/

      - name: Push Docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/sebastianberchtold-hftm/orders-service:1.0.0
          docker push ghcr.io/sebastianberchtold-hftm/inventory-service:1.0.0
