name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest  # Ensure Docker is available here

    steps:
      # Step 1: Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (if needed for the build)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build your services (optional, if needed)
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Build your Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/sebastianberchtold-hftm/orders-service:latest .

      # Step 6: Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/sebastianberchtold-hftm/orders-service:latest
