name: Build Docker Images and Push to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'docker-compose.yml'
      - 'Dockerfile*'
      - '**/*.jar'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push orders-service Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/orders-service:latest .
          docker push ghcr.io/${{ github.repository_owner }}/orders-service:latest

      - name: Build and push inventory-service Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/inventory-service:latest .
          docker push ghcr.io/${{ github.repository_owner }}/inventory-service:latest
